import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import utilStyles from "../styles/utils.module.css";
import Twemoji from "../util/Twemoji";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The bolg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          priority
          src="/images/limmy.jpg"
          height={144}
          width={144}
          className={utilStyles.borderCircle}
        />
        <h1 className={styles.title}>
          Welcome to the Bolg <Twemoji emoji="😀" />
        </h1>

        <br />
        <br />

        <div className={styles.flexContainer}>
          <Link href="/reviews">
            <a className={styles.card}>
              <h2>Book Reviews &rarr;</h2>
              <p>Read my book <Twemoji emoji="📖" /> reviews</p>
            </a>
          </Link>

          <Link href="/posts">
            <a className={styles.card}>
              <h2>Blog &rarr;</h2>
              <p>Learn about useless <Twemoji emoji="🧏🏾‍♂️" /> things!</p>
            </a>
          </Link>
        </div>
      </main>

      {/* <footer className={styles.footer}>
       
          Powered by Pain
          
        
      </footer> */}
    </div>
  );
}
