import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import utilStyles from "../styles/utils.module.css";
import Twemoji from "../util/Twemoji";
import Book from "components/book";
import { bookAuthor, bookTitle, readPercentage } from "util/constants";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The bolg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          priority
          src="/images/limmy.jpg"
          height={144}
          width={144}
          className={utilStyles.borderCircle}
        />
        <br></br>
        <br></br>
        <a
          href="https://github.com/shaikzhafir"
          className={utilStyles.githubLink}
        >
          <Image priority src="/github.svg" height={30} width={30} />
        </a>
        <h1 className={styles.title}>
          Welcome to the Bolg <Twemoji emoji="😀" />
        </h1>

        <br />
        <br />

        <div className={styles.flexContainer}>
          <Book
            bookTitle={bookTitle}
            bookAuthor={bookAuthor}
            readPercentage={readPercentage}
          />
          <div className={styles.tabs}>
            <Link href="/reviews">
              <a className={styles.card}>
                <h2>Book Reviews &rarr;</h2>
                <p>
                  Read my book <Twemoji emoji="📖" /> reviews
                </p>
              </a>
            </Link>
            <Link href="/posts">
              <a className={styles.card}>
                <h2>Blog &rarr;</h2>
                <p>
                  Learn about useless <Twemoji emoji="🧏🏾‍♂️" /> things!
                </p>
              </a>
            </Link>
            <Link href="/notion">
              <a className={styles.card}>
                <h2>Notion Blog &rarr;</h2>
                <p>
                  Learn about useless <Twemoji emoji="🧏🏾‍♂️" /> things but using
                  notion!
                </p>
              </a>
            </Link>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
       
          <p>Were you expecting a normal copyright thing here? well this blog aint normal</p>
          
        
      </footer> */}
    </div>
  );
}
